# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /voucher-image

# Copy the Python scripts into the container
COPY ./ /voucher-image/

# Run main.py when the container launches
CMD ["python", "Main.py"]
#use these commands in terminal
#docker image build -t voucher-app:1.0.0
#docker images(for checking images)
#docker tag voucher-app:1.0.0 ibtsam1/voucher-app:1.0.0
#docker images


