# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy the Python scripts into the container
COPY main.py .
COPY voucheritem.py .
COPY voucher.py .

# Run main.py when the container launches
CMD ["python", "main.py"]
#use these comand in terminal
#docker build -t voucher-app .
#docker run voucher-app


